name: 🚀 Build APP and expose the build as a artifact

on:
  push:
    branches: [develop]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        arch: [x86_64, arm64]
        exclude:
          - os: windows-latest
            arch: arm64
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --force-reinstall setuptools==65.5.0 wheel
          pip install -r requirements.txt
          pip install --no-cache-dir --force-reinstall pyinstaller

      - name: Build with PyInstaller
        run: |
         bash build.sh
        shell: bash


      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: client-${{ runner.os }}-${{ matrix.arch }}
          path: dist/

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
      - uses: ncipollo/release-action@v1
        with:
            artifacts: "client-*"
            tag: v1.0.0-${{ github.run_number }}
