name: 🚀 Build APP and expose the build as a artifact

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-latest, windows-latest]
        arch: [x86_64, arm64]
        exclude:
          - os: windows-latest
            arch: arm64
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --force-reinstall setuptools==65.5.0 wheel
          pip install -r requirements.txt
          pip install --no-cache-dir --force-reinstall pyinstaller

      - name: Build with PyInstaller
        run: |
         bash build.sh
        shell: bash


      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: HardWatch-${{ runner.os }}-${{ matrix.arch }}
          path: dist/

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
      - name: Debug artifacts
        run: ls -R artifacts
      - name: Compress artifacts
        run: |
             mkdir -p zipped_artifacts
              for dir in artifacts/*/; do
                if [ -d "$dir" ]; then
                  dir_name=$(basename "$dir")
                  cd "$dir"
                  zip -r "../../zipped_artifacts/$dir_name.zip" *
                  cd - 
                fi
              done
      - uses: ncipollo/release-action@v1
        with:
            artifacts: "zipped_artifacts/*.zip"
            tag: v1.0.0-${{ github.run_number }}

  deploy-pages:
    needs: release
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Move icon.ico to web/
        run: |
          mkdir -p web
          if [ -f icon.ico ]; then
            mv icon.ico web/
          fi

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: web/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./web